title: nodejs-read-write-files
description: 'I denna kursen kommer du få lära dig:'
template:
  repo: nodejs-read-write-files-template
  name: nodejs-read-write-files
  description: I detta repo kommer du att jobba och pusha filer till.
before:
  - type: createIssue
    title: Välkommen!
    body: start-0.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.closed
    link: '{{ repoUrl }}'
    actions:
      - type: respond
        with: complete-0.md
        issue: 1
      - type: createIssue
        title: Installera Node och sätta upp vår miljö
        body: install-node-1.md
