title: nodejs-read-write-files
description: 'I denna kursen kommer du få lära dig:'
template:
  repo: nodejs-read-write-files-template
  name: nodejs-read-write-files
  description: I detta repo kommer du att jobba och pusha filer till.
before:
  - type: createIssue
    title: Välkommen!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
